import { defineConfig } from 'tsup';
export default defineConfig([
  {
    entry: Object.fromEntries(
      [
        'index',
        'firestore',
        'postgres',
        'dynamodb',
        'cosmos',
        's3',
        'gcs',
        'blob',
        'auth',
        'email',
        'ses',
        'azure-email',
      ].map((name) => [name, `src/cloud/${name}.ts`]),
    ),
    outDir: 'dist/cloud',
    format: ['esm', 'cjs'],
    dts: true,
    clean: true,
    sourcemap: true,
    target: 'node22',
    splitting: false,
    external: [
      'jose',
      '@aws-sdk/client-sesv2',
      '@azure/communication-email',
      'pg',
      '@google-cloud/firestore',
      '@aws-sdk/lib-dynamodb',
      '@aws-sdk/client-dynamodb',
      '@azure/cosmos',
      '@aws-sdk/client-s3',
      '@google-cloud/storage',
      '@azure/storage-blob',
    ],
  },
  {
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    dts: true,
    // Each target owns its files; don't clean the shared parent during parallel builds.
    clean: false,
    sourcemap: true,
    target: 'node22',
    removeNodeProtocol: false,
    shims: true,
  },
  {
    entry: { index: 'src/react.tsx' },
    outDir: 'dist/react',
    format: ['esm', 'cjs'],
    dts: true,
    clean: true,
    sourcemap: true,
    platform: 'browser',
    target: 'es2020',
    splitting: false,
    external: ['react', 'react/jsx-runtime'],
    banner: { js: '"use client";' },
  },
]);
